FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies and clean cache
COPY package*.json ./
RUN npm install

# Copy source files
COPY . .

# Expose port
EXPOSE 3000

# Command to run the app in development mode with hot-reloading
CMD ["npm", "run", "dev"]