FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies and clean cache
COPY package*.json ./
RUN npm install

# Copy source files
COPY . .

# Expose port
EXPOSE 1337

# Command to run the app in development mode
CMD ["npm", "run", "develop"]